//! Emitting the log as byte-deterministic Turtle.
//!
//! Triples accumulate into ordered maps and render subject by subject, so
//! two emissions of the same store are the same bytes — the property the
//! rebuild test protects. Acceptance provenance is PROV-O: an acceptance is
//! attributed to its actor, a version is a revision of its parent, both are
//! generated by their change-set (an activity associated with whoever
//! performed it). `based_on` renders as the literal tokens authors wrote —
//! the vocabulary is open at this milestone, and the graph exposes it
//! without policing it.

use std::collections::{BTreeMap, BTreeSet};

use crate::acceptance::{Acceptance, Revocation};
use crate::store::Store;
use crate::version::VersionRaw;

/// The ledger vocabulary namespace.
pub const NS: &str = "urn:ledger:ns#";
/// PROV-O.
pub const PROV: &str = "http://www.w3.org/ns/prov#";

/// Subject → predicate → objects, all ordered: determinism by construction.
/// Terms are held in their Turtle spelling (prefixed names, `a`); the
/// N-Triples writer expands them, so both serialisations share one graph.
#[derive(Default)]
pub(super) struct Triples(pub(super) BTreeMap<String, BTreeMap<String, BTreeSet<String>>>);

impl Triples {
    fn add(&mut self, subject: &str, predicate: &str, object: String) {
        self.0
            .entry(subject.to_string())
            .or_default()
            .entry(predicate.to_string())
            .or_default()
            .insert(object);
    }

    fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("@prefix ledger: <urn:ledger:ns#> .\n");
        out.push_str("@prefix prov: <http://www.w3.org/ns/prov#> .\n");
        out.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n");
        for (subject, predicates) in &self.0 {
            out.push('\n');
            out.push_str(subject);
            let mut first = true;
            for (predicate, objects) in predicates {
                for object in objects {
                    if first {
                        out.push_str(&format!("\n  {predicate} {object}"));
                        first = false;
                    } else {
                        out.push_str(&format!(" ;\n  {predicate} {object}"));
                    }
                }
            }
            out.push_str(" .\n");
        }
        out
    }
}

/// A string literal escaped the RDF 1.2 canonical way: `ECHAR` for BS, HT,
/// LF, FF, CR, `"` and `\`; uppercase-hex `UCHAR` for the other C0
/// controls, DEL, U+FFFE and U+FFFF. Valid Turtle as well, so the index and
/// the committed export spell every literal identically.
pub(super) fn literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\u{8}' => out.push_str("\\b"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\u{c}' => out.push_str("\\f"),
            '\r' => out.push_str("\\r"),
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{0}'..='\u{1f}' | '\u{7f}' | '\u{fffe}' | '\u{ffff}' => {
                out.push_str(&format!("\\u{:04X}", u32::from(c)));
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn date(value: &chrono::NaiveDate) -> String {
    format!("\"{value}\"^^xsd:date")
}

fn stamp(value: &chrono::DateTime<chrono::Utc>) -> String {
    format!("\"{}\"^^xsd:dateTime", value.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))
}

fn mailto(identity: &crate::identity::Identity) -> String {
    format!("<mailto:{identity}>")
}

fn dec_iri(id: &crate::id::DecisionId) -> String {
    format!("<urn:{id}>")
}

fn hash_iri(hash: &crate::hash::VersionHash) -> String {
    format!("<urn:{hash}>")
}

/// The whole store as one deterministic Turtle document.
pub fn emit(store: &Store) -> String {
    triples(store).render()
}

/// The store's triples, shared by the Turtle index and the N-Triples export.
pub(super) fn triples(store: &Store) -> Triples {
    let mut t = Triples::default();
    for set in &store.sets {
        emit_set(&mut t, set);
    }
    for logged in &store.log {
        let cs = &logged.file;
        let cs_iri = format!("<urn:{}>", cs.id);
        t.add(&cs_iri, "a", "ledger:ChangeSet".into());
        t.add(&cs_iri, "a", "prov:Activity".into());
        t.add(&cs_iri, "prov:wasAssociatedWith", mailto(&cs.created_by));
        t.add(&cs_iri, "prov:endedAtTime", stamp(&cs.created_at));
        if let Some(note) = &cs.note {
            t.add(&cs_iri, "ledger:note", literal(note));
        }
        for parent in &cs.parents {
            t.add(&cs_iri, "ledger:parentChangeSet", format!("<urn:{parent}>"));
        }
        for d in &cs.decisions {
            let iri = dec_iri(&d.id);
            t.add(&iri, "a", "ledger:Decision".into());
            t.add(&iri, "a", "prov:Entity".into());
            t.add(&iri, "ledger:id", literal(&d.id.to_string()));
            t.add(&iri, "ledger:namespace", literal(d.id.namespace()));
            t.add(&iri, "prov:wasAttributedTo", mailto(&d.created_by));
            t.add(&iri, "prov:generatedAtTime", stamp(&d.created_at));
            t.add(&iri, "prov:wasGeneratedBy", cs_iri.clone());
        }
        for v in &cs.versions {
            emit_version(&mut t, v, &cs_iri);
        }
        for a in &cs.acceptances {
            emit_acceptance(&mut t, a, &cs_iri);
        }
        for r in &cs.revocations {
            emit_revocation(&mut t, r);
        }
    }
    t
}

fn emit_set(t: &mut Triples, set: &crate::set::DecisionSet) {
    let iri = format!("<urn:ledger-set:{}>", set.id);
    t.add(&iri, "a", "ledger:DecisionSet".into());
    t.add(&iri, "ledger:id", literal(&set.id));
    t.add(&iri, "ledger:title", literal(&set.title));
    t.add(&iri, "ledger:toleranceFloor", literal(&set.tolerance_floor.to_string()));
    t.add(&iri, "ledger:owner", mailto(&set.owner));
    t.add(&iri, "ledger:createdAt", date(&set.created_at));
}

fn emit_version(t: &mut Triples, v: &VersionRaw, cs_iri: &str) {
    let iri = hash_iri(&v.hash);
    t.add(&iri, "a", "ledger:DecisionVersion".into());
    t.add(&iri, "a", "prov:Entity".into());
    t.add(&iri, "ledger:ofDecision", dec_iri(&v.decision));
    t.add(&iri, "ledger:hash", literal(&v.hash.to_string()));
    t.add(&iri, "ledger:set", format!("<urn:ledger-set:{}>", v.set));
    t.add(&iri, "ledger:statement", literal(&v.statement));
    t.add(&iri, "ledger:floorAtCreation", literal(&v.tolerance_floor_at_creation.to_string()));
    t.add(&iri, "prov:wasGeneratedBy", cs_iri.to_string());
    if let Some(kind) = v.allocation {
        t.add(&iri, "ledger:allocation", literal(kind.as_str()));
    }
    for d in &v.discharge {
        t.add(&iri, "ledger:discharge", literal(&d.to_string()));
    }
    if let Some(stage) = v.discharge_stage {
        t.add(&iri, "ledger:dischargeStage", literal(&stage.to_string()));
    }
    if let Some(actor) = &v.actor {
        t.add(&iri, "ledger:judgmentActor", mailto(actor));
    }
    if let Some(e) = &v.expectation {
        t.add(&iri, "ledger:expectation", literal(e));
    }
    if let Some(e) = &v.exposure {
        t.add(&iri, "ledger:exposure", literal(e));
    }
    if let Some(by) = &v.accepted_by {
        t.add(&iri, "ledger:escapeAcceptedBy", mailto(by));
    }
    if let Some(d) = &v.review_by {
        t.add(&iri, "ledger:reviewBy", date(d));
    }
    if let Some(over) = v.tolerance_override {
        t.add(&iri, "ledger:toleranceOverride", literal(&over.to_string()));
    }
    emit_edges(t, v, &iri);
    if let Some(old) = &v.supersedes {
        t.add(&iri, "ledger:supersedes", dec_iri(old));
    }
    if let Some(parent) = &v.parent {
        t.add(&iri, "prov:wasRevisionOf", hash_iri(parent));
    }
    if let Some(closed) = &v.merged_from {
        t.add(&iri, "ledger:mergedFrom", hash_iri(closed));
    }
}

/// The two edge kinds, under two predicates. Deliberately separate: a query
/// walking `ledger:basedOn` is asking what a decision rests on, and a reopen
/// edge is not an answer to that — the same reason they are separate fields
/// on the wire.
fn emit_edges(t: &mut Triples, v: &VersionRaw, iri: &str) {
    for basis in &v.based_on {
        t.add(iri, "ledger:basedOn", literal(basis.as_str()));
    }
    for edge in &v.revisit_if {
        t.add(iri, "ledger:revisitIf", literal(edge.as_str()));
    }
}

fn emit_acceptance(t: &mut Triples, a: &Acceptance, cs_iri: &str) {
    let iri = format!("<urn:{}>", a.id);
    t.add(&iri, "a", "ledger:Acceptance".into());
    t.add(&iri, "a", "prov:Entity".into());
    t.add(&iri, "ledger:ofDecision", dec_iri(&a.decision));
    t.add(&iri, "ledger:signsVersion", hash_iri(&a.version));
    t.add(&iri, "prov:wasAttributedTo", mailto(&a.actor));
    t.add(&iri, "prov:generatedAtTime", stamp(&a.at));
    t.add(&iri, "ledger:scope", literal(&a.scope.to_string()));
    t.add(&iri, "prov:wasGeneratedBy", cs_iri.to_string());
    if let Some(expires) = &a.expires_at {
        t.add(&iri, "ledger:expiresAt", date(expires));
    }
}

fn emit_revocation(t: &mut Triples, r: &Revocation) {
    let iri = format!("<urn:{}>", r.acceptance);
    t.add(&iri, "ledger:revokedAt", stamp(&r.at));
    t.add(&iri, "ledger:revokedBy", mailto(&r.by));
    t.add(&iri, "ledger:revocationReason", literal(&r.reason));
}
